### ISSUE TITLE
libffi: ppc64 check fails

### ISSUE THREAD

**Issue by pullmoll** [void-ppc/void-packages#17] opened 2019-05-08 04:49 UTC
I can confirm https://github.com/libffi/libffi/issues/377 on the ppc64 G5.
This is possibly related to `mozjs52` and `mozjs60` failing for ppc64 (and ppc).
First [failing test](https://github.com/libffi/libffi/blob/80d07104c33045ea34a4d5185600495dc7461a12/testsuite/libffi.call/cls_64byte.c#L113) in cls_64byte.c
Next [failing tests](https://github.com/libffi/libffi/blob/80d07104c33045ea34a4d5185600495dc7461a12/testsuite/libffi.call/problem1.c#L84) in problem1.c
Both are related to libffi handling of structs containing double variables. Perhaps an alignment issue?

**Comment by q66** [comment] 2019-05-08 14:42
Hm, hard to say. I believe the `mozjs` packages are fine here and the issue is caused by cross compiling. With libffi that doesn't seem to be the case (and it seems to affect both LE and BE, if the bug report is still relevant).

**Comment by pullmoll** [comment] 2019-05-08 17:12
The issue with mozjs52 is not caused by cross compiling, no. I verified that a natively built mozjs52 also segfaults when called by polkitd and executing an instruction in mozjs52.
```
2019-05-08T19:08:25.775840+02:00 g5 kernel: [   17.468145] polkitd[730]: segfault (11) at 188 nip 71ebba7a621c lr 71ebbab9bb3c code 1 in libmozjs-52.so.0[71ebba5d0000+a80000]
2019-05-08T19:08:25.775844+02:00 g5 kernel: [   17.469585] polkitd[730]: code: 00000000 00090001 80030000 60000000 60000000 3c4c0092 38421100 7c0802a6
2019-05-08T19:08:25.775848+02:00 g5 kernel: [   17.470979] polkitd[730]: code: fbc1fff0 fbe1fff8 f8010010 f821ffd1 <e8630000> 7c3f0b78 4bf1a4fd e8410018
```
I'll try to investigate the `./xbps-src check libffi` fail on the G5 and see what goes on... just need to learn a little more ppc64 assembler.

For the libffi failure you can try the same on your ppc64le. I added the `checkdepends="dejagnu"` to libffi which is required for the check target.

**Comment by q66** [comment] 2019-08-10 17:38
@pullmoll I'll be importing a fix for `libffi` later this evening.

I also got `mozjs52` and `mozjs60` to run - turns out the issue is cross-compiled `libicu` carrying in little endian data into big endian target. So we should for now add something like this in `libicu`:

```
if [ "$XBPS_ENDIAN" -ne "$XBPS_TARGET_ENDIAN" ]; then
    nocross=yes
fi
```

**Comment by q66** [comment] 2019-08-10 17:48
Looks like `libicu` cross compilation could be fixed by manually converting the data files to big endian with `icupkg -tb`... could be done using the previously built host version

**Comment by q66** [comment] 2019-08-10 17:58
Hm, okay, looks like the respective test in `libffi` is still failing, but at least the `mozjs*` packages run now...

**Comment by q66** [comment] 2019-08-10 18:02
Good news:

```
		=== libffi tests ===

Schedule of variations:
    unix

Running target unix
Using /usr/share/dejagnu/baseboards/unix.exp as board description file for target.
Using /usr/share/dejagnu/config/unix.exp as generic interface file for target.
Using ../../testsuite/config/default.exp as tool-and-target-specific interface file.
Running ../../testsuite/libffi.call/call.exp ...

		=== libffi Summary ===

# of expected passes		1870
make[3]: Leaving directory '/builddir/libffi-3.2.1/powerpc64-unknown-linux-gnu/testsuite'
make[2]: Leaving directory '/builddir/libffi-3.2.1/powerpc64-unknown-linux-gnu/testsuite'
Making check in man
make[2]: Entering directory '/builddir/libffi-3.2.1/powerpc64-unknown-linux-gnu/man'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/builddir/libffi-3.2.1/powerpc64-unknown-linux-gnu/man'
make[2]: Entering directory '/builddir/libffi-3.2.1/powerpc64-unknown-linux-gnu'
make[2]: Leaving directory '/builddir/libffi-3.2.1/powerpc64-unknown-linux-gnu'
make[1]: Leaving directory '/builddir/libffi-3.2.1/powerpc64-unknown-linux-gnu'
```

I'll close this once the fixes are imported.

**Comment by q66** [comment] 2019-08-10 22:38
Fixed by https://github.com/void-linux/void-packages/pull/13580

**Closed by q66** 2019-08-10 22:38 UTC
